### PR TITLE
Tournament system

### PR DESCRIPTION
**Pull request by gclement42**
- now the frontend is connected to backend, you can create tournament, join it and unsubscribe
- if the tournament is empty, I delete it
- I removed host, is_private and password fields in tournament models for simplifying the work
- I added 'makemigrations' in entrypoint
- I blocked online game if the user is not logged in

### CODE REVIEW

**Review by MarcelCerdan — CHANGES_REQUESTED** [review]
There is a few minor problems : 
     -When the number of max players is too big, there is an error 400 returned by the fetch in createTournament.js line 9 but nothing is displayed to inform the user.
     -If the tournament's name is too long, the number of player in the tournament is hidden in the list of the tournaments when we want to join one.
     -When you join a tournament and then click the arrow in the top left corner there is a little bug when you see the main menu of the game and then return in the tournament's lobby.

**Comment by gclement42** [comment]
I fixed the bug mentioned by @MarcelCerdan, and I added a pop up error in create tournament to make it clearer and I added a button for actualize tournament list

**Review by boulatrousse — APPROVED** [review]
Nice job, tournaments work fine for me

**Review by maujogue — APPROVED** [review]
- some delay on my mac when people join and leave tournaments, nothing too crazy
- you should grey out the online game section if user is not connected, to be more explicit
- also reduce the maximum number of players when creating tournaments

**Review by MarcelCerdan — APPROVED** [review]

**Pull request closed without merging**
