### PR TITLE
Translations

### PR DESCRIPTION
**Pull request by maujogue**
### Translations ? Wait, @gclement42 won't have to read english anymore ?

That's right. Please go and read the `frontend/js/modules/translationsModule/documentation.md` for an overview of the new functionalities to enable translations in your code.

#### What was / was not done ?

- We currently support french, english and spanish, but the language switcher is already ready for italian, german, portuguese and Chinese. We will only have to create other JSON files with the appropriate translations to enable those. For now, when clicking those the site is translated in English.
-  I tried to go through every piece of language that's already in the project, but from now on this will be each and everyone's job to maintain its new code's translations. 
- While the translations of the pages are injected on site load, the game's translation are injected each time a change is detected in the `id="game` div, so it should work both ways.
- From now on, when you create new code, please update at least the english JSON file, so that we only have to drag it into chat gpt to generate all the other languages.
- I haven't checked that much the quality on the translations, that we will do when finalising the project.

#### How is the language stored ?

Both in the `lang` cookie and in the new `lang` attribute of the customUser model.
When user **is not** logged in, it sets the language to the default language of the browser. Then it's stored as a Cookie.
When user **is** logged in, it sets the language to the preffered language of the user. Then as a Cookie for less backend call.

### CODE REVIEW

**Comment by boulatrousse** [comment]
I get this error all the time : 

image

Am I supposed to do something to remove those errors ?

**Review by gclement42 — COMMENTED** [review]
Screenshot from 2024-06-06 10-22-32

**Comment by maujogue** [comment]
As I thought, Firefox does not support _import assert_, so I replaced it with a classic fetch. Should now work on both firefox and chrome.

**Review by gclement42 — COMMENTED** [review]
My favorite language is Chinese, unfortunately only english, french and spanish work. 
remove icons from languages ​​that don't work

**Comment by maujogue** [comment]
> My favorite language is Chinese, unfortunately only english, french and spanish work. remove icons from languages ​​that don't work

done

**Review by LezardSC — APPROVED** [review]
Except french and spanish, every language is in fact english.
Also not everything is translated. Of course, things related to the game is not up to you, and we will take care of that in the future, but some buttons and all errors messages are only in english, for example:
image

I still approve the PR. This is a good start.

**Review by gclement42 — COMMENTED** [review]
When I change the language, it remains on the penultimate language chosen, for example if I choose French, then Spanish, the menu will be in French. on the other hand in the game no problem

**Review by gclement42 — APPROVED** [review]

**Review by boulatrousse — APPROVED** [review]
looks good to me except the edit form that stays in english

**Pull request merged**
