### PR TITLE
Merge game dashboard

### PR DESCRIPTION
**Pull request by maujogue**
### Revamped Dashboard

About and game paged are now merged with the dashboard, which means we no longer have pages (except for emailValidation page).
The design is final, but we still need to check all translations, please don't mention anything like that in this PR.
There also is new toast notification for showAlert.
Also, **change username tournament** is done

### CODE REVIEW

**Review by gclement42 — APPROVED** [review]
Globally it's good, but some error remains :

- There are still aesthetic improvements to be made
-  the responsiveness of the game, in particular the tournaments
- the tournament brackets are broken (maybe because of the tournament username)

**Review by boulatrousse — CHANGES_REQUESTED** [review]
- History text is too black
- When no match was played fix the message
- Notification for register and login, maybe put the notification back to the previous place
- Wrap in notification
- Update banner and profile picture does not work (csrf token issue)
- When you try to update your profile and click on `Save changes`, it reloads and it does not save the changes

**Review by boulatrousse — CHANGES_REQUESTED** [review]
- The hour on the notification is not correct. Between HH:00 and HH:09, the alerte does not display the 0 (picture taken at 13:01) : 

Screenshot from 2024-07-11 13-01-28

- When you try to change the tournament username it's not case-sensitive. `Billy` and `BillY` are different but it should not be like that. It's probably a backend issue, I'll check later.
- When you change your email, there is no notification to inform the user that he should check his emails.
- The `About` button on the profile does nothing.
- When you are on another user profile, his username is not displayed : 

Screenshot from 2024-07-11 13-13-54

Also, I think it's kind of weird that there's the message "Play your first game" on another user's profile

- When you change the lang, there is a page's reload and it automatically log you out.

**Review by boulatrousse — APPROVED** [review]
Everything works !! Great job and great new design

**Review by LezardSC — DISMISSED** [review]
-The game in local seems to be broken. Sometimes the keys works but most of the time they don't. The online seems to works but can't really test without lagging way to much on the macs...

-I got this error each time I go in the online menu.
image

-At full screen on the Macs, the tournament menu is bigger than the window.
image

-the shape of the profile pictures are weird. I know we don't do responsive so we have to decide on which screen we will gonna get the corrections (certainly the dells) and be sure the shape is good there.

-I sent a friend request. The friend request is said as 'sent' but I got the error 'this user does not exist' in the same time, and the user didn't received anything.

**Comment by maujogue** [comment]
Friend request were broke on master already since commit f41b35c, we should have been more careful when checking @boulatrousse PR.
I made the listeners for the game based on document and no more on the div, so you don't have to click on the div anymore and it should work better now.
Added style for the avatar and banner so that they always have a 1:1 and 3:2 aspect ratio.

**Review by boulatrousse — APPROVED** [review]
Everything seems good to me !

**Review by gclement42 — APPROVED** [review]
Ok for me, I noticed some small problems, I noted them in the excel file

**Pull request merged**
