### PR TITLE
Blockchain Module

### PR DESCRIPTION
**Pull request by LezardSC**
Results of a tournament is now push on the blockchain, for more security.
The only visible change is that at the end of a tournament, you have a new button which send you to the receipt address of the transaction.
The button will be gray with 'waiting for transaction' on it until the transaction is complete. When it's the case, you will be able to click and go to the page.

When you are on it, it will look like that:
image

Click on 'click to show more' then 'view input as' and select 'utf-8'
image

It's hard to read, but you will have all the informations of the tournament here.

Here's an example:
image

All informations are set in that order:
-tournament Name
-tournament Winner
-matches (round, player 1, player 1 score, player 2, player 2 score, match winner)

You can check if the infos are correct.

If you go in an older tournament in the history, the button will be available in the same way.

A transaction takes usually less than 30 seconds, but sometimes it can take more than 5 minutes. If you're unlucky you will have to be patient.

You can check here all the transactions made on our contract address, and when:
https://sepolia.etherscan.io/address/0x9a0747a3555f00aa610553e07cb84f15e60fd5cf
The contract address is in the env otherwise.

### CODE REVIEW

**Review by gclement42 — DISMISSED** [review]
Good, but the looser of the final is not redirected to the ranking page

**Review by maujogue — DISMISSED** [review]
it worked great for me, but now that we tested it you absolutely have to remove the private key and wallet adress that are hard-coded in `tournament_contract.py`.
Even the ones in .env.prod and `.env.dev` should not be pushed through github, but passed to us through another secured way(I looked into secret managing but it's too complicated to implement at this stage and for only the 42api and sepolia keys, so we'll do it via whatsapp or something encrypted).
Also, please merge with master now that translations are merged :)

**Comment by maujogue** [comment]
image

**Comment by jayson687** [comment]
The best hackers I have seen are  d a r k w e b p r o g r a m m e r @ g m a i l . c o m   , they got me $15,000 via hack

**Review by boulatrousse — APPROVED** [review]

**Review by gclement42 — APPROVED** [review]

**Pull request merged**
