### PR TITLE
Friendlist front

### PR DESCRIPTION
**Pull request by maujogue**
### FriendList 

You can search people, see their profile and stats and then send a friend request if you're not friend already, or delete the friendship if you are.
The friendlist, friend request list and add_friend button are dynamic with the websockets. You can see your friend's status too.

### CODE REVIEW

**Review by gclement42 — COMMENTED** [review]
- I don't know why but here when I search 'Herrrmann' I have a error message 
image

- If I search a user while in the game tab,
I'm not automatically redirected to the profile page

- Inbox z-index is not good
image

and some ideas: 

- change Inbox pos and style,a notification bubble would be more aesthetic
- In Inbox accept and denied btn is not animated, when I click I don't have a feedback

**Review by LezardSC — CHANGES_REQUESTED** [review]
List of issues I found:
-I don't think the fade when the profile of another player appear is necessary. It's pretty ugly tbh.
-We need a notification of the inbox when we have a friend request.
-You can send a friend request to someone, and the someone can send a friend request too. Then if one of those accept, they are friend but the notification is still here, and you can accept it again and receive the notification of the friend adding again.
Not a big deal BUT if you keep the friend request, unfriend him, then click on the friend request to add it again it works.

-When you're in the game page and search someone, you are not directly rediriged on the dashboard page and I think you should.

-I would like an enlightment when we put the cursor on the guy in the friend list.

-We can't click on the profile of a guy in the friend list before refreshing the page. Once I refreshed once I can.

-If I'm on the profile of someone and he does a game, its stats doesn't update themselves, and if I refresh I'm back to my own profile. I think it's ok if the stats doesn't update in real time, but when we refresh we should still be on the guy profile I think.

**Comment by maujogue** [comment]
image
All mentionned issues should be fixed!

**Review by LezardSC — APPROVED** [review]
Except the things you said you cannot change, everything looks way better. Good job !

**Comment by MarcelCerdan** [comment]
The spanish beacon for notifications doesn't exist.

**Review by MarcelCerdan — APPROVED** [review]

**Pull request merged**
