### PR TITLE
Tournaments

### PR DESCRIPTION
**Pull request by LezardSC**
It's been a long time since we didn't update the tournaments in the master branch, but here we are, with the tournaments almost over.
We are now able to create, join and play tournaments until a winner is decided.

Now dev launch on localhost(127.0.0.1)
- Otherwise to launch on the school network use prod (depending on your computer in the cluster the IP address may change, use ifconfig to get the right ip and update DJANGO_ALLOWED_HOSTS in .env file)
- Then, simply connect on the website and create a tournament.
- After you created the tournament, you will have to open new windows in order to connect with new users to join the tournament. The maximum number of players is 8. Kindly try with odd number of players and odd number of matches.
- When the tournament is full, it will start automatically after a few seconds.
- When the game is over, you will be able to see the bracket, and when everyone finished their matches, the second part start after a few seconds, and go one until the tournament is over.
- After a tournament is done, you can see it in the history. When you click on a tournament you will have access to the ranking and the bracket.

Features you should be able to see:
-Fully playable tournament
-Bracket between the matches
-Loading screen animation before matches
-Ending screen depending of weither you win or lose.
-ranking at the end of the tournament.
-Tournaments history

You will have a lot of things to try if you want to be rigorous.
Enjoy playing against yourself !

### CODE REVIEW

**Review by boulatrousse — DISMISSED** [review]
Nice job!!

However, I've noticed a few issues.

- First of all, all websockets are in `ws 8080` instead of `wss 8000`.
- After a tournament, when you click on `show bracket`, it changes the space backgroup.
- Replace `semi-finale` with `semi-final`.
- In stats, every match has a red cross, even if you won the match.
- When the last match of a tournament starts and one of the two player leave, it displays the end screen. It's a little abrupt, maybe add a pop-up that says "your opponent left before the beginning of the match"

The rest seems good to me !

**Comment by LezardSC** [comment]
> Nice job!!
> 
> However, I've noticed a few issues.
> 
>     * First of all, all websockets are in `ws 8080` instead of `wss 8000`.
> 
>     * After a tournament, when you click on `show bracket`, it changes the space backgroup.
> 
>     * Replace `semi-finale` with `semi-final`.
> 
>     * In stats, every match has a red cross, even if you won the match.
> 
>     * When the last match of a tournament starts and one of the two player leave, it displays the end screen. It's a little abrupt, maybe add a pop-up that says "your opponent left before the beginning of the match"
> 
> 
> The rest seems good to me !

the websockets url and the typo with semi-final and final are fixed. The match history always showing a red cross is already fixed in another branch. The space background reset will not be fixed.

For the deconnexion we're working on it

**Review by boulatrousse — CHANGES_REQUESTED** [review]
I had two errors : 
- The first one : history recovers 2 histories instead of one and it crash the tournamenent
- The second one : when a browser crashes during a tournament, the waiting screen is locked and loads endlessly

**Review by maujogue — APPROVED** [review]
My tests were not extensive but they worked great. I tested 2,3, 4 players tournaments, player quitting, quitting then joining back, timeout on waiting screen, history seems okay. 
there are a few language typos but we'll look into this when finalising translations.

**Review by boulatrousse — COMMENTED** [review]
Everything seems good to me but when the tournament is over, there is a slight delay before the result is display.

**Review by boulatrousse — APPROVED** [review]
Everything seems good to me but when the tournament is over, there is a slight delay before the result is display.

**Pull request merged**
